In [1]:
import numpy as np

In [3]:
a = np.array([[1,2,3], [4,5,6]])
print(a)
print(a.ndim)
print(a.shape)
print(a.sum(axis=0), a.sum(axis=1))

[[1 2 3]
 [4 5 6]]
2
(2, 3)
[5 7 9] [ 6 15]


In [8]:
b = np.array([[[1,2,3], [4,5,6]],[[11,12,13],[14,15,16]]])
print(b)
print(b.ndim)
print(b.shape)
print(b.sum(axis=0))
print(b.sum(axis=1))
print(b.sum(axis=2))

A = np.array([1,2,3])
B = np.array([4,5,6])
C = np.array([11,12,13])
D = np.array([14,15,16])
new_b = np.array([[A, B], [C, D]])
print(new_b)

[[[ 1  2  3]
  [ 4  5  6]]

 [[11 12 13]
  [14 15 16]]]
3
(2, 2, 3)
[[12 14 16]
 [18 20 22]]
[[ 5  7  9]
 [25 27 29]]
[[ 6 15]
 [36 45]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[11 12 13]
  [14 15 16]]]
