# Python: Types and Sequences

In [3]:
type("This is a string"), type(None), type(1), type(1.0), type(lambda x: 1)

(str, NoneType, int, float, function)

In [4]:
x = (1, 'a', 2, 'b')
type(x)

tuple

In [5]:
x = [1, 'a', 2, 'b']
type(x)

list

In [7]:
[1]*3

[1, 1, 1]

In [8]:
x = 'This is a string'
print(x[0]) 
print(x[0:1])
print(x[0:2])
print(x[-4:-2])

firstname = 'Christopher Arthur Hansen Brooks'.split(' ')[0] # [0] selects the first element of the list
lastname = 'Christopher Arthur Hansen Brooks'.split(' ')[-1] # [-1] selects the last element of the list
print(firstname)
print(lastname)

T
T
Th
ri
Christopher
Brooks


In [9]:
'Chris' + 2

TypeError: can only concatenate str (not "int") to str

In [10]:
x = {'Christopher Brooks': 'brooksch@umich.edu', 'Bill Gates': 'billg@microsoft.com'}
x['Christopher Brooks'] # Retrieve a value by using the indexing operator

'brooksch@umich.edu'

In [11]:
x['Kevyn Collins-Thompson'] = None
x['Kevyn Collins-Thompson']

In [12]:
for name in x:
    print(x[name])

brooksch@umich.edu
billg@microsoft.com
None


In [13]:
for email in x.values():
    print(email)

brooksch@umich.edu
billg@microsoft.com
None


In [14]:
for name, email in x.items():
    print(name)
    print(email)

Christopher Brooks
brooksch@umich.edu
Bill Gates
billg@microsoft.com
Kevyn Collins-Thompson
None


In [15]:
x = ('Christopher', 'Brooks', 'brooksch@umich.edu')
fname, lname, email = x

# Reading and Writing CSV files

In [16]:
import csv

%precision 2

with open('mpg.csv') as csvfile:
    mpg = list(csv.DictReader(csvfile))
    
mpg[:3] # The first three dictionaries in our list.
len(mpg)
mpg[0].keys() # keys gives us the column names of our csv.
sum(float(d['cty']) for d in mpg) / len(mpg)
cylinders = set(d['cyl'] for d in mpg)

CtyMpgByCyl = []

for c in cylinders: # iterate over all the cylinder levels
    summpg = 0
    cyltypecount = 0
    for d in mpg: # iterate over all dictionaries
        if d['cyl'] == c: # if the cylinder level type matches,
            summpg += float(d['cty']) # add the cty mpg
            cyltypecount += 1 # increment the count
    CtyMpgByCyl.append((c, summpg / cyltypecount)) # append the tuple ('cylinder', 'avg mpg')

CtyMpgByCyl.sort(key=lambda x: x[0])

FileNotFoundError: [Errno 2] No such file or directory: 'mpg.csv'

# Python: Dates and Times

In [17]:
import datetime as dt
import time as tm

time returns the current time in seconds since the Epoch. (January 1st, 1970)

In [18]:
tm.time()

1567611894.49

In [20]:
dtnow = dt.datetime.fromtimestamp(tm.time())
dtnow

datetime.datetime(2019, 9, 4, 23, 45, 5, 839859)

In [21]:
dtnow.year, dtnow.month, dtnow.day, dtnow.hour, dtnow.minute, dtnow.second # get year, month, day, etc.from a datetime

(2019, 9, 4, 23, 45, 5)

In [22]:
delta = dt.timedelta(days = 100) # create a timedelta of 100 days
delta

datetime.timedelta(days=100)

In [23]:
today = dt.date.today()

In [24]:
today - delta # the date 100 days ago

datetime.date(2019, 5, 27)

# NumPy

In [25]:
import numpy as np

## Creating Arrays

In [26]:
mylist = [1, 2, 3]
x = np.array(mylist)
x

array([1, 2, 3])

In [27]:
y = np.array([4, 5, 6])
y

array([4, 5, 6])

In [28]:
m = np.array([[7, 8, 9], [10, 11, 12]])
m

array([[ 7,  8,  9],
       [10, 11, 12]])

In [29]:
m.shape

(2, 3)

In [30]:
n = np.arange(0, 30, 2) # start at 0 count up by 2, stop before 30
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [31]:
n = n.reshape(3, 5) # reshape array to be 3x5
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [32]:
o = np.linspace(0, 4, 9) # return 9 evenly spaced values from 0 to 4
o

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [33]:
o.resize(3, 3)
o

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

In [34]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [35]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [36]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [37]:
np.diag(y)

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

In [38]:
np.array([1, 2, 3] * 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [39]:
np.repeat([1, 2, 3], 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

#### Combining Arrays

In [40]:
p = np.ones([2, 3], int)
p

array([[1, 1, 1],
       [1, 1, 1]])

In [41]:
np.vstack([p, 2*p])

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

In [42]:
np.hstack([p, 2*p])

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

## Operations

In [43]:
print(x + y) # elementwise addition     [1 2 3] + [4 5 6] = [5  7  9]
print(x - y) # elementwise subtraction  [1 2 3] - [4 5 6] = [-3 -3 -3]
print(x * y) # elementwise multiplication  [1 2 3] * [4 5 6] = [4  10  18]
print(x / y) # elementwise divison         [1 2 3] / [4 5 6] = [0.25  0.4  0.5]
print(x**2) # elementwise power  [1 2 3] ^2 =  [1 4 9]

[5 7 9]
[-3 -3 -3]


<br>
**Dot Product:**  

$ \begin{bmatrix}x_1 \ x_2 \ x_3\end{bmatrix}
\cdot
\begin{bmatrix}y_1 \\ y_2 \\ y_3\end{bmatrix}
= x_1 y_1 + x_2 y_2 + x_3 y_3$

In [44]:
x.dot(y) # dot product  1*4 + 2*5 + 3*6

32

In [45]:
z = np.array([y, y**2])
print(len(z)) # number of rows of array

2


In [47]:
z

array([[ 4,  5,  6],
       [16, 25, 36]])

In [48]:
z.shape

(2, 3)

In [49]:
z.T

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

In [50]:
z.T.shape

(3, 2)

In [51]:
z.dtype

dtype('int64')

In [52]:
z = z.astype('f')
z.dtype

dtype('float32')

## Math functions

In [53]:
a = np.array([-4, -2, 1, 3, 5])

In [54]:
a.sum()

3

In [55]:
a.max()

5

In [56]:
a.min()

-4

In [57]:
a.mean()

0.6

In [58]:
a.std()

3.2619012860600183

In [59]:
a.argmax()

4

In [60]:
a.argmin()

0

## Indexing / Slicing

In [61]:
s = np.arange(13)**2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

In [62]:
s[0], s[4], s[-1]

(0, 16, 144)

In [63]:
s[1:5]

array([ 1,  4,  9, 16])

In [64]:
s[-4:]

array([ 81, 100, 121, 144])

In [65]:
s[-5::-2]

array([64, 36, 16,  4,  0])

In [66]:
r = np.arange(36)
r.resize((6, 6))
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [67]:
r[2, 2]

14

In [68]:
r[3, 3:6]

array([21, 22, 23])

In [69]:
r[:2, :-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

In [70]:
r[-1, ::2]

array([30, 32, 34])

In [71]:
r[r > 30]

array([31, 32, 33, 34, 35])

In [72]:
r[r > 30] = 30
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

## Copying Data

In [73]:
r2 = r[:3,:3]
r2

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

In [74]:
r2[:] = 0
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [75]:
r

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [76]:
r_copy = r.copy()
r_copy

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [77]:
r_copy[:] = 10
print(r_copy, '\n')
print(r)

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]] 

[[ 0  0  0  3  4  5]
 [ 0  0  0  9 10 11]
 [ 0  0  0 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 30 30 30 30 30]]


## Iterating Over Arrays

In [79]:
test = np.random.randint(0, 10, (4,3))
test

array([[1, 2, 0],
       [0, 2, 7],
       [4, 5, 6],
       [6, 9, 6]])

In [80]:
for row in test:
    print(row)

[1 2 0]
[0 2 7]
[4 5 6]
[6 9 6]


In [81]:
for i in range(len(test)):
    print(test[i])

[1 2 0]
[0 2 7]
[4 5 6]
[6 9 6]


In [82]:
for i, row in enumerate(test):
    print('row', i, 'is', row)

row 0 is [1 2 0]
row 1 is [0 2 7]
row 2 is [4 5 6]
row 3 is [6 9 6]


In [83]:
test2 = test**2
test2

array([[ 1,  4,  0],
       [ 0,  4, 49],
       [16, 25, 36],
       [36, 81, 36]])

In [84]:
for i, j in zip(test, test2):
    print(i,'+',j,'=',i+j)

[1 2 0] + [1 4 0] = [2 6 0]
[0 2 7] + [ 0  4 49] = [ 0  6 56]
[4 5 6] + [16 25 36] = [20 30 42]
[6 9 6] + [36 81 36] = [42 90 42]
